pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli
    command: ["cat"]
    tty: true

  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["cat"]
    tty: true
    securityContext:
      runAsUser: 0
      readOnlyRootFilesystem: false
    env:
    - name: KUBECONFIG
      value: /kube/config
    volumeMounts:
    - name: kubeconfig-secret
      mountPath: /kube/config
      subPath: kubeconfig

  - name: dind
    image: docker:dind
    args: ["--storage-driver=overlay2"]
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-config
      mountPath: /etc/docker/daemon.json
      subPath: daemon.json

  volumes:
  - name: docker-config
    configMap:
      name: docker-daemon-config
  - name: kubeconfig-secret
    secret:
      secretName: kubeconfig-secret
'''
        }
    }

    environment {
        IMAGE_LOCAL   = "trustvote-frontend:latest"
        REGISTRY      = "nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085"
        REGISTRY_PATH = "pavan-project/trustvote-frontend"
        IMAGE_TAGGED  = "${REGISTRY}/${REGISTRY_PATH}:v${env.BUILD_NUMBER}"
       SONAR_PROJECT = "TrustVote-Frontend"
        NAMESPACE     = "2401195"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                container('dind') {
                    dir('Trust-Vote/client') {
                        sh '''
                          sleep 15
                          echo "Building frontend Docker image..."
                          docker build -t ${IMAGE_LOCAL} .
                          docker image ls
                        '''
                    }
                }
            }
        }

  stage('SonarQube Analysis') {
    steps {
        container('sonar-scanner') {
            withCredentials([string(credentialsId: 'sonar-token-2401195', variable: 'SONAR_TOKEN')]) {
                dir('Trust-Vote/client') {
                    sh '''
                        sonar-scanner \
                            -Dsonar.projectKey=TrustVote-Frontend \
                            -Dsonar.sources=src \
                            -Dsonar.host.url=http://my-sonarqube-sonarqube.sonarqube.svc.cluster.local:9000 \
                            -Dsonar.token=$SONAR_TOKEN
                    '''
                }
            }
        }
    }
}

        stage('Login to Docker Registry') {
            steps {
                container('dind') {
                    withCredentials([usernamePassword(
                        credentialsId: 'nexus-docker-2401195',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh '''
                          echo $DOCKER_PASS | docker login ${REGISTRY} -u $DOCKER_USER --password-stdin
                        '''
                    }
                }
            }
        }

        stage('Build - Tag - Push Image') {
            steps {
                container('dind') {
                    sh '''
                      docker tag ${IMAGE_LOCAL} ${IMAGE_TAGGED}
                      docker push ${IMAGE_TAGGED}
                    '''
                }
            }
        }

        stage('Deploy Frontend to K8s') {
            steps {
                container('kubectl') {
                    dir('Trust-Vote/k8s-deployment') {
                        sh '''
                          kubectl apply -f trustvote-frontend-deployment.yaml
                          kubectl rollout status deployment/trustvote-frontend-deployment -n ${NAMESPACE}
                        '''
                    }
                }
            }
        }
    }
}
